version: "3.4"

services:
  guestbook:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - "5000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 1s
    depends_on:
        - "redis-master"
        - "redis-slave"
    networks:
      - front-tier
      - back-tier

  redis-master:
    image: k8s.gcr.io/redis:e2e
    container_name: redis-master
    ports: ["6379"]
    networks:
      - back-tier
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 1s


  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v1
    container_name: redis-slave
    ports: ["6380:6379"]
    networks:
      - back-tier
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 1s

networks:
  front-tier:
  back-tier:
