version: "3.4"

services:
  guestbook:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
      - "5000:80"
    healthcheck:
## Add healthcheck here
    

    depends_on:
## Services that should start first 
    


    networks:

## Create 2 networks 

  redis-master:
    image: k8s.gcr.io/redis:e2e
    container_name: redis-master
    ports: ["6379"]
    networks:
## Network for master goes here
    
    healthcheck:
## Add health check to confirm redis is online 

  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v1
    container_name: redis-slave
    ports: ["6380:6379"]
    networks:
## Network for redis 
    healthcheck:
## Add healtcheck for redis 

networks:
## List networks for frontend and backend 
